version: '3'

services:
  api:
    container_name: api
    image: api-ts
    ports:
      - 3002:3002

  mysql:
    container_name: mysql-docker
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test-api
    ports:
      - 3308:3306
